INSERT INTO `medialookup`.`genre` (`name`, `notes`) 
VALUES ("Action", ""), 
("Krimi", ""), 
("Drama", ""), 
 ("Fantasy", ""), 
 ("Horror", ""), 
 ("Komödie", ""), 
 ("Romanze", ""), 
 ("Science-Fiction", ""), 
 ("Sport", ""), 
 ("Thriller", ""), 
 ("Mystery", ""), 
 ("Krieg", ""), 
 ("Western", ""),
 ("SitCom", "");
